#!/usr/bin/env bash
set -euo pipefail

# Generates deploy/vm2/.env for the reservation worker.
#
# DB_PASSWORD MUST match VM1's database credentials (the ticketing-service
# repo's deploy/vm1/.env), so it is required and never generated here:
#
#   DB_PASSWORD=<from-vm1/.env> ./deploy/generate-env.sh <dockerhub-repo>
#
# IMAGE_REPO may be $1 or $IMAGE_REPO (prompted if neither). All other values
# are optional and read from the environment; anything left blank is written
# as a REPLACE_ME placeholder for you to fill in later.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Resolve IMAGE_REPO ---
IMAGE_REPO="${1:-${IMAGE_REPO:-}}"
if [[ -z "$IMAGE_REPO" ]]; then
  read -rp "Docker Hub repo (e.g. alvin/ticketing-service-worker): " IMAGE_REPO
fi
if [[ -z "$IMAGE_REPO" ]]; then
  echo "ERROR: IMAGE_REPO is required" >&2
  exit 1
fi

# --- DB password is shared with VM1: require it, never invent it ---
DB_PASSWORD="${DB_PASSWORD:-}"
if [[ -z "$DB_PASSWORD" ]]; then
  echo "ERROR: DB_PASSWORD must be set — pass the same value as the" >&2
  echo "ticketing-service repo's deploy/vm1/.env." >&2
  exit 1
fi

# --- Optional values (env overrides, else placeholders) ---
WORKER_TAG="${WORKER_TAG:-worker}"
DB_USERNAME="${DB_USERNAME:-postgres}"
DB_DATABASE="${DB_DATABASE:-ticketing}"
VM1_PUBLIC_IP="${VM1_PUBLIC_IP:-REPLACE_WITH_VM1_EXTERNAL_IP}"
STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY:-sk_test_REPLACE_ME}"

# --- Refuse to silently clobber an existing env ---
if [[ -f "$SCRIPT_DIR/vm2/.env" ]]; then
  echo "WARNING: $SCRIPT_DIR/vm2/.env already exists."
  read -rp "Overwrite? This may change the worker's database credentials. [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
fi

# --- Write vm2/.env ---
cat > "$SCRIPT_DIR/vm2/.env" <<EOF
# Generated by deploy/generate-env.sh — do not commit.
IMAGE_REPO=$IMAGE_REPO
WORKER_TAG=$WORKER_TAG
VM1_PUBLIC_IP=$VM1_PUBLIC_IP
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD
DB_DATABASE=$DB_DATABASE
STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
EOF

echo ""
echo "✅ Wrote $SCRIPT_DIR/vm2/.env"
echo ""
echo "Next: fill in any REPLACE_ME placeholders (VM1_PUBLIC_IP, Stripe key),"
echo "then follow deploy/README.md."
