#!/usr/bin/env bash
set -euo pipefail

# Generates deploy/vm1/.env and deploy/vm2/.env with a fresh random DB password.
#
# Usage:
#   ./deploy/generate-env.sh <dockerhub-repo>      # e.g. alvin/ticketing-service
#
#   # or pass everything in one go, no editing needed:
#   IMAGE_REPO=alvin/ticketing-service \
#   VM1_PUBLIC_IP=34.1.2.3 \
#   STRIPE_SECRET_KEY=sk_test_... \
#   STRIPE_WEBHOOK_SECRET=whsec_... \
#   ./deploy/generate-env.sh
#
# IMAGE_REPO may be $1 or $IMAGE_REPO (prompted if neither). All other values are
# optional and read from the environment; anything left blank is written as a
# REPLACE_ME placeholder for you to fill in later.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Resolve IMAGE_REPO ---
IMAGE_REPO="${1:-${IMAGE_REPO:-}}"
if [[ -z "$IMAGE_REPO" ]]; then
  read -rp "Docker Hub repo (e.g. alvin/ticketing-service): " IMAGE_REPO
fi
if [[ -z "$IMAGE_REPO" ]]; then
  echo "ERROR: IMAGE_REPO is required" >&2
  exit 1
fi

# --- Optional values (env overrides, else placeholders) ---
API_TAG="${API_TAG:-api}"
WORKER_TAG="${WORKER_TAG:-worker}"
DB_USERNAME="${DB_USERNAME:-postgres}"
DB_DATABASE="${DB_DATABASE:-ticketing}"
VM1_PUBLIC_IP="${VM1_PUBLIC_IP:-REPLACE_WITH_VM1_EXTERNAL_IP}"
STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY:-sk_test_REPLACE_ME}"
STRIPE_WEBHOOK_SECRET="${STRIPE_WEBHOOK_SECRET:-whsec_REPLACE_ME}"
CLIENT_URL="${CLIENT_URL:-http://localhost:4242}"

# --- Generate a strong DB password (hex: safe in .env, URLs, and Postgres) ---
DB_PASSWORD="$(openssl rand -hex 32)"

# --- Refuse to silently clobber an existing env (would orphan the DB) ---
for f in "$SCRIPT_DIR/vm1/.env" "$SCRIPT_DIR/vm2/.env"; do
  if [[ -f "$f" ]]; then
    echo "WARNING: $f already exists."
    read -rp "Overwrite? This regenerates DB_PASSWORD and may orphan the existing DB. [y/N] " ans
    [[ "$ans" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
  fi
done

# --- Write vm1/.env ---
cat > "$SCRIPT_DIR/vm1/.env" <<EOF
# Generated by deploy/generate-env.sh — do not commit.
IMAGE_REPO=$IMAGE_REPO
API_TAG=$API_TAG
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD
DB_DATABASE=$DB_DATABASE
STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
CLIENT_URL=$CLIENT_URL
EOF

# --- Write vm2/.env ---
cat > "$SCRIPT_DIR/vm2/.env" <<EOF
# Generated by deploy/generate-env.sh — do not commit.
IMAGE_REPO=$IMAGE_REPO
WORKER_TAG=$WORKER_TAG
VM1_PUBLIC_IP=$VM1_PUBLIC_IP
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD
DB_DATABASE=$DB_DATABASE
STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
EOF

echo ""
echo "✅ Wrote $SCRIPT_DIR/vm1/.env and $SCRIPT_DIR/vm2/.env"
echo "   DB_PASSWORD: $DB_PASSWORD"
echo ""
echo "Next: fill in any REPLACE_ME placeholders (VM1_PUBLIC_IP, Stripe keys),"
echo "then follow deploy/README.md."
